services:
  lisp:
    build: .
    container_name: lisp-server
    restart: always
    ports:
      - "8080:8080"
    networks:
      - app-network
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

  nginx:
    image: nginx:alpine # minimal version of nginx
    container_name: nginx-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - lisp
    networks:
      - app-network
    restart: always
    read_only: true
    tmpfs:
      - /var/cache/nginx
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

networks:
  app-network:
    driver: bridge
